// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetR.Web.Infrastructure;

namespace NetR.Web.Migrations
{
    [DbContext(typeof(BionoContext))]
    partial class BionoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("NetR.Web.Infrastructure.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("NetR.Web.Infrastructure.Entities.ServiceConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<string>("ResponsibleServer");

                    b.Property<string>("ServerName");

                    b.Property<string>("ServiceName");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("ServiceConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
